### ISSUE TITLE
Hi - trying to get in touch 

### ISSUE THREAD

**Issue by mfahampshire** [hyahatiph-labs/xmrbc-rs#1]
Hi - apologies for leaving this as an issue but it was the only way I could find to get in touch with you. 

Drop me an email on [max@nymtech.net](mailto:max@nymtech.net), I'd like to chat about something related to this code :)

**Comment by reemuru** [comment]
Thanks for reaching out Max. Will be in the irc. I created a room for the project as well. Closing this.

https://matrix.to/#/#xmrbc-rs:matrix.org
